# name: Create Tag on PR Merge

# on:
#   pull_request:
#     types:
#       - closed

# jobs:
#   create_tag:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out code
#         uses: actions/checkout@v2

#       - name: Set Git user identity
#         run: |
          # git config user.name "Mangesh Bangale"
          # git config user.email "mangeshbangale27@gmail.com"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

#       - name: Create tag
#         id: create_tag
#         run: |
#           git tag v1.0.0   # Replace with the desired tag name
#           git push origin --tags
#         env:
#           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}


name: Create Tag and GitHub Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Mangesh Bangale"
          git config user.email "mangeshbangale27@gmail.com"

      - name: Create Tag
        id: create-tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "::set-output name=TAG_NAME::$TAG_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Create Draft Release
        id: create-release
        if: success()
        run: |
          TAG_NAME=${{ steps.create-tag.outputs.TAG_NAME }}
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/releases" \
            -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            -d '{
              "tag_name": "$TAG_NAME",
              "name": "$TAG_NAME",
              "body": "Draft Release for $TAG_NAME",
              "draft": true,
              "prerelease": false
            }'
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}