# name: Create Tag on PR Merge

# on:
#   pull_request:
#     types:
#       - closed

# jobs:
#   create_tag:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out code
#         uses: actions/checkout@v2

#       - name: Set Git user identity
#         run: |
          # git config user.name "Mangesh Bangale"
          # git config user.email "mangeshbangale27@gmail.com"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

#       - name: Create tag
#         id: create_tag
#         run: |
#           git tag v1.0.0   # Replace with the desired tag name
#           git push origin --tags
#         env:
#           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}


name: Create Tag and GitHub Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Mangesh Bangale"
          git config user.email "mangeshbangale27@gmail.com"

      - name: Create Tag
        id: create-tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create Draft Release
        id: create-release
        if: success()
        run: |
          #!/usr/bin/bash
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{"tag_name":"v20230914063512","target_commitish":"master","name":"v20230914063512","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":true}'