name: PR Title Check

on:
  pull_request:
    types: 
      - opened
    branches:
      - master

jobs:
  pr_title_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        id: title-check
        run: |
          TITLE_REGEX="Release v[0-9]\.[0-9]\.[0-9]"
          if [[ ! "$PR_TITLE" =~ $TITLE_REGEX ]]; then
            echo "::set-output name=invalid_title::true"
            echo "VALID_TITLE=false" >> $GITHUB_ENV
          fi
      - name: Send Warning Comment
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        if: steps.title-check.outputs.invalid_title == 'true'
        run: |
          curl -X POST -H "Authorization: token $GIT_TOKEN" \
            -d "{\"body\":\":warning: **Warning:** Please follow the correct PR title format. Pr title must contain release version.\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
