name: PR Title Check

on:
  pull_request:
    types: 
      - opened
    branches:
      - master

jobs:
  pr_title_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        id: title-check
        run: |
          if [[ ${{ github.event.pull_request.head.ref }} == "master" ]]; then
            TITLE_REGEX="Release v[0-9]\.[0-9]\.[0-9]"
            if [[ ! "$PR_TITLE" =~ $TITLE_REGEX ]]; then
              echo "invalid_title=true" >> $GITHUB_OUTPUT
              echo "warn_message="pull request title must contains Release vx.x.x." >> $GITHUB_OUTPUT
            fi
          fi
          
      - name: Send Warning Comment
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        if: steps.title-check.outputs.invalid_title == 'true'
        run: |
          curl -X POST -H "Authorization: token $GIT_TOKEN" \
            -d "{\"body\":\":warning: **Warning:** ${{ steps.title-check.outputs.warn_message }}\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
